version: '3.8'
services:
  api:
    image: ong-cloud-api
    build:
      context: .
      target: production
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
      NODE_ENV: production
